feature: support multi-language, add Chinese
tetratelabs/getistio.io pull request #60
Opened 2021-02-03 12:31 UTC by rootsongjc

- Added multi-language support
- Modified the structure of the document
- Fixed the style of language switch button
- Modified the baseURL
- Added a blog (Chinese and English)

2021-02-03 14:36 UTC, lunchboxav requested changes

2021-02-03 14:36 UTC, lunchboxav commented on config.toml
> +baseURL = "https://getistio.io/"
can we keep using baseURL = "/" because, otherwise it will be broken because we haven't moved from getistio-demo.netlify.app to getistio.io

2021-02-03 16:09 UTC, rootsongjc commented on config.toml
> +baseURL = "https://getistio.io/"
I use `relURL` and `relLangURL` so that the relative paths can be independent of the domain name.

2021-02-03 18:01 UTC, peterj commented on config.toml
> +################################### English anguage #####################################
typo: should be "language"

2021-02-03 18:05 UTC, peterj commented on content/en/blog/netease-qingzhou-istio-practice/index.md
> +![](008eGmZEly1gna7t5zhrjj310n0u00y7.jpg)
add the 'alt' text for images

2021-02-04 02:01 UTC, lunchboxav commented on config.toml
> +baseURL = "https://getistio.io/"
actually no, this will break a lot of links that relies on `baseURL`. for example those box menu on the homepage. 

![box-menu](https://user-images.githubusercontent.com/1574827/106834219-96d50500-66c7-11eb-862a-07f62998bc5f.PNG)


If you want to use `relURL` can you not change `baseURL` ? Otherwise, if this `relURL` is absolutely required, then you have to change all the instance of links that use `baseURL` to `relURL`. Otherwise, we will have several broken links.

2021-02-04 02:43 UTC, rootsongjc commented on config.toml
> +baseURL = "https://getistio.io/"
I have fixed all linking issues in the site and can now use relative links directly, independent of baseURL.

2021-02-04 08:08 UTC, lunchboxav approved these changes
ok @rootsongjc let's merge this for now. thank you very much for working on this.

2021-02-04 08:11 UTC, merged